Marryme/Marryme.WebUI/Controllers/MemberChatController.cs
using Marryme.BAL;
using Marryme.BAL.MarrymeClientManager;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;


namespace Marryme.WebUI.Controllers
{
    public class MemberChatController : Controller
    {
        // GET: MemberChat
        public ActionResult LiveChat()
        {
            if (Session["MemberId"] != null)
            {
                ViewBag.MemberId = Session["MemberId"];
                Int64 memberId = Convert.ToInt64(Session["MemberId"]);
                ViewBag.Member = PersonalProfileCardManager.GetChatMemberProfileInfo(memberId);
                return View();
            }
            return RedirectToAction("Index", "Home");
        }
        public JsonResult FetchChatMembers(bool isFriend, string searchKeyWord)
        {
            long memberId = Convert.ToInt64(Session["MemberId"]);
            return Json(MemberChatManager.FetchChatMemberList(memberId, isFriend, searchKeyWord), JsonRequestBehavior.AllowGet);
        }
        public JsonResult FetchMemberChatConversation(long selectedMemberId)
        {
            long currentMemberId = Convert.ToInt64(Session["MemberId"]);
            return Json(MemberChatManager.FetchMemberChatConversation(currentMemberId, selectedMemberId), JsonRequestBehavior.AllowGet);
        }
        public JsonResult SendChatFriendRequest(long selectedMemberId)
        {
            long currentMemberId = Convert.ToInt64(Session["MemberId"]);
            return Json(MemberChatManager.SendChatFriendRequest(currentMemberId, selectedMemberId), JsonRequestBehavior.AllowGet);
        }
        public JsonResult BlockFriend(long selectedMemberId, long friendRequestId)
        {
            long currentMemberId = Convert.ToInt64(Session["MemberId"]);
            return Json(MemberChatManager.BlockFriend(currentMemberId, selectedMemberId, friendRequestId), JsonRequestBehavior.AllowGet);
        }
        public JsonResult UnBlockOrAcceptFriend(long friendRequestId)
        {
            return Json(MemberChatManager.UnBlockOrAcceptFriend(friendRequestId), JsonRequestBehavior.AllowGet);
        }
        public JsonResult UploadImage()
        {
            foreach (string file in Request.Files)
            {
                return Json(MemberChatManager.UploadImage(Request.Files[file]), JsonRequestBehavior.AllowGet);
            }
            return Json(new Message(), JsonRequestBehavior.AllowGet);
        }
        public JsonResult CheckForMessagePermission()
        {
            long fromId = Session["MemberId"].ToInt64();
            var packageDetail = Static.DbContext.MemberPackageSubscriptionDetails.FirstOrDefault(s => s.MemberId == fromId && s.IsActive);
            if (packageDetail is null)
            {
                return Json(false, JsonRequestBehavior.AllowGet);
            }
            if (packageDetail.UsedNoOfChatMessages <= packageDetail.TotalNoOfChatMessages)
            {
                return Json(true, JsonRequestBehavior.AllowGet);
            }
            return Json(false, JsonRequestBehavior.AllowGet);
        }
        public ActionResult UnReadCounterByMemberId()
        {
            return Json(MemberChatManager.UnReadCounterByMemberId(Convert.ToInt64(Session["MemberId"])), JsonRequestBehavior.AllowGet);
        }
        public ActionResult MarkMessagesAsReadByMemberId()
        {
            MemberChatManager.MarkMessagesAsReadByMemberId(Convert.ToInt64(Session["MemberId"]));
            return Json(true, JsonRequestBehavior.AllowGet);
        }

    }
}

Marryme/Marryme.WebUI/Controllers/MemberController.cs
using Marryme.BAL;
using Marryme.BAL.MarrymeClientManager;
using Marryme.BAL.ViewModels;
using Marryme.DAL;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Marryme.WebUI.Controllers
{
    [SessionTimeout]
    public class MemberController : Controller
    {
        // GET: Member         
        public ActionResult ProfileWizard()
        {
            return View();
        }
        public ActionResult MyMatches()
        {
            return View();
        }
        public ActionResult ProfileRequirement()
        {
            return View();
        }        
        public ActionResult MemberDetail()
        {
            return View();
        }
        public ActionResult UploadDocs()
        {
            return View();
        }
        public ActionResult DocumentList()
        {
            return View();
        }
        public ActionResult ChangePassword()
        {
            return View();
        }
        //public JavaScriptResult Doclist()
        //{
        //    Message msg = MemberManger.Doclist();
        //    return Json(msg, JsonRequestBehavior.AllowGet);
        //}
        public JsonResult DeleteImage(string docId)
        {
            var documentId = Convert.ToInt32(docId);
            var MemberId = Convert.ToInt32(Session["MemberId"]);
            return Json(MemberManger.DeleteImage(MemberId, documentId), JsonRequestBehavior.AllowGet);
        }
        public JsonResult MemberDetailById(string MemberId)
        {
            Int64 memberId = Convert.ToInt64(MemberId.DecodeQueryString());
            Message msg = MemberManger.GetMemberDetailById(memberId);
            return Json(msg, JsonRequestBehavior.AllowGet);
        }
        //public JsonResult ViewPhone(string memberId)
        //{
        //    return Json(MemberManger.ViewPhone(memberId.DecodeQueryString().ToInt64(),Session["MemberId"].ToInt64()), JsonRequestBehavior.AllowGet);
        //}
        public ActionResult WifeDetail()
        {
            return View();
        }
        [HttpPost]
        public JsonResult SaveWifeDetail()
        {
            var member = Request.Unvalidated.Form["WifeDetail"].ToString().Deserialize<ExsitingWifeDetailVM>();
            member.MemberId = Convert.ToInt32(Session["MemberId"]);
            return Json(ExsitingWifeDetailManager.SaveWifeDetail(member), JsonRequestBehavior.AllowGet);

        }
        //[HttpPost]
        //public JsonResult SaveKidzDetail(List<WifeKidzDetailVM> member)
        //{
        //    //var member = Request.Unvalidated.Form["WifeKidsDetail"].ToString().Deserialize<WifeKidzDetailVM>();
        //    int MemberId = Convert.ToInt32(Session["MemberId"]);
        //    return Json(ExsitingWifeDetailManager.SaveKidzDetail(member, MemberId), JsonRequestBehavior.AllowGet);

        //}
       
      
        [HttpPost]
        public JsonResult FetchWifeDetailById()
        {
            Int64 memberId = Convert.ToInt64(Session["MemberId"]);
            Message msg = ExsitingWifeDetailManager.WifeDetailGetById(memberId);
            if (msg == null)
            {
                msg = new Message();
            }
            return Json(msg, JsonRequestBehavior.AllowGet);
        }

        public JsonResult FetchWifeDetailById(int ExsitingWife)
        {
            Int64 memberId = Convert.ToInt64(Session["MemberId"]);
            Message msg = ExsitingWifeDetailManager.WifeDetailGetBy_ExistingWifeNo(memberId, ExsitingWife);
            if (msg == null)
            {
                msg = new Message();
            }
            return Json(msg, JsonRequestBehavior.AllowGet);
        }
        [HttpPost]
        public JsonResult FetchWifeKidzDetailById()
        {
            Int64 memberId = Convert.ToInt64(Session["MemberId"]);
            Message msg = ExsitingWifeDetailManager.WifeKidsDetailGetById(memberId);
            if (msg == null)
            {
                msg = new Message();
            }
            return Json(msg, JsonRequestBehavior.AllowGet);
        }
        [HttpGet]
        public JsonResult FetchWifeKidzDetailById(int ExsitingWife)
        {
            Int64 memberId = Convert.ToInt64(Session["MemberId"]);
            Message msg = ExsitingWifeDetailManager.WifeKidsDetailGet_ByWifeNo(memberId,ExsitingWife);
            if (msg == null)
            {
                msg = new Message();
            }
            return Json(msg, JsonRequestBehavior.AllowGet);
        }
        public ActionResult MarriagePolicy()
        {
            return View();
        }
        public ActionResult DivorcePolicy()
        {
            return View();
        }
        public ActionResult AcceptanceCriteria()
        {
            return View();
        }
        public JsonResult AcceptanceQuestionList()
        {
            long memberId = 0;
            string memberGender = "";
            if (Session["MemberId"] != null)
            {
                memberId = Convert.ToInt64(Session["MemberId"]);
                memberGender = Convert.ToString(Session["Gender"]);
            }
            return Json(AcceptanceCriteriaManager.AcceptanceQuestionList(memberId), JsonRequestBehavior.AllowGet);
        }
        [HttpPost]
        public JsonResult SaveCriteria()
        {
            var member = Request.Unvalidated.Form["Acceptance"].ToString().Deserialize<AcceptanceCriteriaVM>();
            member.MemberId = Convert.ToInt32(Session["MemberId"]);
            return Json(AcceptanceCriteriaManager.SaveCriteria(member), JsonRequestBehavior.AllowGet);
           
        }        
        public JsonResult FetchAcceptanceCriteriaById()
        {
            Int64 memberId = Convert.ToInt64(Session["MemberId"]);
            Message msg = AcceptanceCriteriaManager.AcceptanceCriteriaGetById(memberId);
            if (msg == null)
            {
                msg = new Message();
            }
            return Json(msg, JsonRequestBehavior.AllowGet);
        }
        public JsonResult PersonalInfo()
        {
            var member = Request.Unvalidated.Form["PersonalInfo"].ToString().Deserialize<MemberRegistration>();
            member.Id = Convert.ToInt32(Session["MemberId"]);
            member.Email = Convert.ToString(Session["Email"]);
            return Json(MemberManger.PersonalInfo(member, Request.Files["Image"]), JsonRequestBehavior.AllowGet);
        }
        public JsonResult DocFile()
        {
            var member = Request.Unvalidated.Form["UploadDocs"].ToString().Deserialize<UploadDocumentsVM>();
            member.MemberId = Convert.ToInt32(Session["MemberId"]);
            return Json(MemberManger.DocFile(member, Request.Files["Image"]), JsonRequestBehavior.AllowGet);
        }
        public JsonResult DocumentListById()
        {
            Int64 memberId = Convert.ToInt64(Session["MemberId"]);
            Message msg = MemberManger.DocumentListById(memberId);
            if (msg == null)
            {
                msg = new Message();
            }
            return Json(msg, JsonRequestBehavior.AllowGet);
        }
        public JsonResult PersonalInfoGetById()
        {
            Int64 memberId = Convert.ToInt64(Session["MemberId"]);
            Message msg = MemberManger.PersonalInfoGetById(memberId);
            if (msg == null)
            {
                msg = new Message();
            }
            return Json(msg, JsonRequestBehavior.AllowGet);
        }
        public JsonResult FetchProfileLocationDetail()
        {
            Int64 memberId = Convert.ToInt64(Session["MemberId"]);
            Message msg = LocationManager.FetchProfileLocationDetail(memberId);
            if (msg == null)
            {
                msg = new Message();
            }
            return Json(msg, JsonRequestBehavior.AllowGet);
        }
        public JsonResult EducationInfo()
        {
            var member = Request.Unvalidated.Form["EducationInfo"].ToString().Deserialize<MemberEducationDetail>();
            member.MemberId = Convert.ToUInt32(Session["MemberId"]);
            return Json(EducationManager.EducationInfo(member), JsonRequestBehavior.AllowGet);
        }
        public JsonResult FetchProfileEducationDetail()
        {
            Int64 memberId = Convert.ToInt64(Session["MemberId"]);
            Message msg = EducationManager.FetchProfileEducationDetail(memberId);
            if (msg == null)
            {
                msg = new Message();
            }
            return Json(msg, JsonRequestBehavior.AllowGet);
        }
        public JsonResult FamilyInfo(MemberFamilyDetail model)
        {
            var member = Request.Unvalidated.Form["FamilyInfo"].ToString().Deserialize<MemberFamilyDetail>();
            member.MemberId = Convert.ToUInt32(Session["MemberId"]);
            return Json(FamilyManager.FamilyInfo(member), JsonRequestBehavior.AllowGet);
        }
        public JsonResult FetchProfileFamilyDetail()
        {
            Int64 memberId = Convert.ToInt64(Session["MemberId"]);
            Message msg = FamilyManager.FetchProfileFamilyDetail(memberId);
            if (msg == null)
            {
                msg = new Message();
            }
            return Json(msg, JsonRequestBehavior.AllowGet);
        }
        public JsonResult ReligiousInfo()
        {
            var member = Request.Unvalidated.Form["ReligiousInfo"].ToString().Deserialize<MemberReligiousDetail>();
            member.MemberId = Convert.ToUInt32(Session["MemberId"]);
            return Json(ReligiousManager.ReligiousInfo(member), JsonRequestBehavior.AllowGet);
        }
        public JsonResult FetchProfileReligiousDetail()
        {
            Int64 memberId = Convert.ToInt64(Session["MemberId"]);
            Message msg = ReligiousManager.FetchProfileReligiousDetail(memberId);
            if (msg == null)
            {
                msg = new Message();
            }

Marryme/Marryme.WebUI/Views/Shared/_RegistrarLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    <link href="~/Content/bootstrap 4/css/MENTOR2style.css" rel="stylesheet" />
    <link href="~/assets/vendor/toastr/toastr.css" rel="stylesheet" />
    <link href="~/assets/vendor/iziToast/iziToast-min.css" rel="stylesheet" />
    <script src="~/Scripts/jquery/jquery.min.js"></script>
    <script src="~/Scripts/angular.js"></script>
    <script src="~/assets/vendor/toastr/toastr.js"></script>
    <script src="~/assets/vendor/iziToast/iziToast-min.js"></script>
    <script src="~/assets/vendor/parsleyjs/js/parsley.js"></script>
    <script src="~/assets/vendor/php-email-form/validate.js"></script>
    <script src="~/Angular/Generic.js"></script>
    <script src="~/assets/js/ui-bootstrap-tpls-0.13.4.min.js"></script>
    <script src="~/Scripts/ng-file-upload.min.js"></script>
    <script src="~/Angular/Method.js"></script>
    <script src="~/Angular/Filter.js"></script>
    <script src="~/Angular/Service.js"></script>
    <link href="~/assets/vendor/parsleyjs/css/parsley.css" rel="stylesheet" />
    <link href="~/assets/assets/Side-Bar/style.css" rel="stylesheet" />
    <link href="~/assets/vendor/icofont/icofont.min.css" rel="stylesheet" />
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.2/css/all.min.css" rel="stylesheet" />
    <script src="~/Scripts/peerjs.min.js"></script>
    @Scripts.Render("~/bundles/modernizr")
    <style>
        .dropdown:hover > .dropdown-menu {
            display: block;
        }
        .navbar-light .navbar-nav .nav-link {
            color: rgb(40 38 38);
        }
        /*.navbar-light .navbar-nav .nav-link {
            color: #f8f9fa;
        }

            .navbar-light .navbar-nav .nav-link:hover {
                color: #f8f9fa;
            }

            .navbar-light .navbar-nav .nav-link.active {
                color: #0a79e9;
            }*/

        .text-success {
            color: #28a745 !important;
            background-color: white;
            border-radius: 10px;
            padding: 5px 13px;
            box-shadow: 7px 4px 8px #1e7e46;
            box-shadow: 34px;
        }

        .form-group {
            margin-bottom: 0.3rem
        }

        .btn-sky {
            color: #17a2b8 !important;
            font-weight: 600;
            font-size: 13px;
            letter-spacing: 0.5px;
            text-transform: uppercase;
            display: inline-block;
            padding: 12px 30px;
            border-radius: 50px;
            transition: 0.3s;
            line-height: 1;
            color: white;
            border: 2px solid #17a2b8;
        }

        .btn-success {
            color: #f8f9fa;
            background-color: #28a745;
            border-color: #0062cc;
            border: 2px solid #879aab;
        }

        .card-header {
            padding: 0.3rem 1.25rem;
            margin-bottom: 0;
            background-color: rgba(0, 0, 0, 0.03);
            border-bottom: 1px solid rgba(0, 0, 0, 0.125);
        }

        .btn-sky:hover {
            background: #6ee388;
            color: #fff !important;
        }
    </style>
</head>
<body>
    <div>
        <div ng-app="MarrymeClientModule" class="wrapper align-items-stretch">
            @if (Session["MemberId"] != null)
            {
                <header class="fixed-top">
                    <div class="navbar navbar-expand-md navbar-light bg-white ">

                        <a class="navbar-brand text-success" href="#" style=" font-size: xx-large; font-weight: bolder; padding-left: 5px;">1234wife</a>
                        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarContent">
                            <span class="navbar-toggler-icon"></span>
                        </button>
                        <div class="collapse navbar-collapse text-center" id="navbarContent">
                            <ul class="navbar-nav ml-auto pull-right" style="font-weight: 700;">
                                <li class="nav-item">
                                    <a class="nav-link active" onclick="green()" id="Green" href="@Url.Action("Index","Home")"><i class="fa fa-home mr-3"></i>Home</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link active" onclick="green1()" id="Green9" href="@Url.Action("ProfileWizard","Member")"><i class="fa fa-user mr-3"></i>My Profile</a>
                                </li>
                                @*<li class="nav-item">
                                        <a class="nav-link active" onclick="green1()" id="Green1" href="@Url.Action("MemberList","Member")"><i class="fa fa-list mr-3"></i>Member List</a>
                                    </li>*@
                                <li class="nav-item">
                                    <a class="nav-link active" onclick="green1()" id="Green10" href="#"><i class="fa fa-info-circle mr-3"></i>About</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link active" onclick="green7()" id="Green7" href="#l"><i class="fa fa-contact-card mr-3"></i>Contact</a>
                                </li>
                                <li>
                                    <a href="@Url.Action("Logout","Account")" type="button" class="btn btn-success" style="border-radius: 30px; width: 130px;"><i class="fa fa-sign-out mr-3"></i>Log Out</a>
                                </li>
                            </ul>
                        </div>
                    </div>
                </header>
                <!--Nav Bar End-->
                <div class=" body-content">
                    @RenderBody()
                    <hr />
                    <footer>
                        <p class="text-center">&copy; @DateTime.Now.Year - 1234Wife.com</p>
                    </footer>
                    <div id="preloader"></div>
                    @if (Session["MemberId"] != null && !Request.Url.AbsolutePath.ToLower().Contains("/memberchat/livechat"))
                    {
                        <a href="@Url.Action("LiveChat","MemberChat")" class="back-to-top chatbtn">
                            <span id="chatCounter" class="badge text-success position-absolute" style="right:50px;bottom:50px;">0</span>
                            <i class="far fa-comments text-success" style="font-size:50px"></i>
                        </a>
                        <script>
                            Get('/MemberChat/UnReadCounterByMemberId').then(function (result) {
                                //    console.log(result);
                                $('#chatCounter').html(result.Data);
                            });
                        </script>
                    }
                </div>
            }
            else
            {
                <!--Nav Bar Start-->
                <header class="fixed-top" style="display:inline-block">
                    <div class="navbar navbar-expand-lg navbar-light bg-info text-white ">

                        <a class="navbar-brand text-success" href="#" style="font-size: xx-large; font-weight: bolder; padding-left:5px;">1234wife</a>
                        @*<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarContent">
                                <span class="navbar-toggler-icon"></span>
                            </button>*@
                        <div class="collapse navbar-collapse text-center" id="navbarContent">
                            <ul class="navbar-nav ml-auto pull-right" style="font-weight: 700;">
                                <li class="nav-item">
                                    <a class="nav-link active" onclick="green()" id="Green" href="@Url.Action("Index","Home")"><span class="fa fa-home mr-3"></span>Home</a>
                                </li>
                                <li class="nav-item">
                                    @*<a class="nav-link active" onclick="green4()" id="Green4" href="#">Events</a>*@
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link active" onclick="green1()" id="Green1" href="#"><i class="fa fa-circle-info mr-3"></i>About</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link active" onclick="green7()" id="Green7" href="#l"><i class="fa fa-contact-card mr-3"></i>Contact</a>
                                </li>
                                <li class="nav-item dropdown">
                                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                        <i class="fa fa-registered mr-3"></i> Register
                                    </a>
                                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                        <a class="nav-link active" onclick="green8()" id="Green8"
                                           href="/Account/Registeration/">
                                            Member Register
                                        </a>
                                        <div class="dropdown-divider"></div>
                                        <a class="nav-link active" onclick="green8()" id="Green9"
                                           href="/Account/RegisterRegistrar/">
                                            Registrar Register
                                        </a>
                                    </div>
                                </li>
                                @*<li class="nav-item">
                                        <a class="nav-link active" onclick="green8()" id="Green8" href="/Account/Registeration/"><i class="fa fa-registered mr-3"></i>Register</a>
                                    </li>*@
                                <a href="@Url.Action("Login","Account")" type="button" class="btn btn-success" style="border-radius: 30px; width: 130px; height:40px"><i class="fa fa-sign-in mr-3"></i>Login</a>
                            </ul>
                        </div>
                    </div>
                </header>
                <!--Nav Bar End-->
                <div class=" body-content">
                    @RenderBody()
                    <hr />
                    <footer>
                        <p>&copy; @DateTime.Now.Year - 1234Wife.com</p>
                    </footer>

                </div>
            }


            @*@Scripts.Render("~/bundles/jquery")*@
            @Scripts.Render("~/bundles/bootstrap")
            @RenderSection("scripts", required: false)


            <div class="modal fade" id="loginModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                <div class="modal-dialog" role="document">
                    <div class="modal-content">
                        <div class="modal-header bg-success">
                            <h5 class="modal-title text-white" id="exampleModalLabel">Login</h5>
                            <button class="close text-white" type="button" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">×</span>
                            </button>
                        </div>
                        <div class="modal-body">
                            @Html.Partial("~/Views/Partials/_Login.cshtml")
                        </div>
                        <div class="modal-footer bg-success">
                            <button class="btn btn-outline-light" type="button" data-dismiss="modal">Cancel</button>
                            <br />
                        </div>
                    </div>
                </div>
            </div>
            @*@Html.Partial("~/Views/Partials/_ChangePassword.cshtml")*@
        </div>
    </div>
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>